dist: trusty
language: scala
jdk:
  - oraclejdk8
scala:
  - 2.12.15
sudo: false
# From http://www.scala-sbt.org/1.0/docs/Travis-CI-with-sbt.html#%28Experimental%29+Reusing+Ivy+cache
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
    - $HOME/.m2
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
# no spam
notifications:
  email: false
